#!/usr/bin/env python3
"""Build kb/index.md grouping all dialogue pages by CEFR + language + source.

Also writes/updates kb/sources/*.md with a lessons-covered list per book.
"""
import re
from collections import defaultdict
from datetime import date
from pathlib import Path

BASE = Path(__file__).parent
KB = BASE / "kb"


def parse_frontmatter(text: str) -> dict:
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def main():
    dialogues = sorted((KB / "dialogues").glob("*.md"))
    by_lang_cefr = defaultdict(lambda: defaultdict(list))
    by_source = defaultdict(list)

    for f in dialogues:
        text = f.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        lang = fm.get("target_lang", "?")
        cefr = fm.get("cefr", "?")
        src = fm.get("source", "?")
        lesson = int(fm.get("lesson", "0")) if fm.get("lesson", "").isdigit() else 0
        title = fm.get("title", "").strip('"')
        slug = fm.get("slug", f.stem)
        by_lang_cefr[lang][cefr].append((lesson, slug, title, src))
        by_source[src].append((lesson, slug, title, cefr))

    lines = [
        "# Index",
        "",
        "Generated by `_build_index.py` from frontmatter. Updated automatically.",
        "",
        f"_Last build: {date.today().isoformat()}_",
        "",
        "## By language and CEFR",
    ]
    cefr_order = ["A1", "A2", "B1", "B2", "C1", "C2"]
    lang_name = {"fr": "French", "en": "English"}
    for lang in sorted(by_lang_cefr):
        lines += ["", f"### {lang_name.get(lang, lang)} ({lang})"]
        for cefr in cefr_order:
            items = sorted(by_lang_cefr[lang].get(cefr, []))
            if not items:
                continue
            lines += ["", f"#### {cefr} ({len(items)} dialogues)"]
            for lesson, slug, title, src in items:
                lines.append(f"- L{lesson:03d} [[dialogues/{slug}]] — {title}  ({src})")

    lines += ["", "## By source"]
    for src in sorted(by_source):
        items = sorted(by_source[src])
        lines += ["", f"### {src} ({len(items)} dialogues)"]
        for lesson, slug, title, cefr in items:
            lines.append(f"- L{lesson:03d} [{cefr}] [[dialogues/{slug}]] — {title}")

    # Coverage summary at the top
    coverage = {l: {c: len(by_lang_cefr[l].get(c, [])) for c in cefr_order}
                for l in by_lang_cefr}
    cov_lines = ["", "## Coverage summary", ""]
    cov_lines.append("| language | A1 | A2 | B1 | B2 | C1 | C2 | total |")
    cov_lines.append("|---|---|---|---|---|---|---|---|")
    for l in sorted(coverage):
        c = coverage[l]
        total = sum(c.values())
        cov_lines.append(
            f"| {lang_name.get(l, l)} | {c['A1']} | {c['A2']} | {c['B1']} | "
            f"{c['B2']} | {c['C1']} | {c['C2']} | {total} |"
        )

    final = "\n".join(lines[:5] + cov_lines + lines[5:]) + "\n"
    (KB / "index.md").write_text(final, encoding="utf-8")
    print(f"index built. {sum(len(v) for v in by_source.values())} dialogues across "
          f"{len(by_source)} sources, {sum(sum(c.values()) for c in coverage.values())} cefr-tagged.")


if __name__ == "__main__":
    main()
